let store = {
  questions: [
    {
      questionNumber: 'Сурак 1',
      question: ' Графикалық редактор-бұл бағдарламалық жасақтама өнімі…',
      var1: 'a)	сызбаларды жасау кезінде ДК ресурстарын басқару',
      var2: 'b)	іс жүргізу процесінде мәтіндік ақпаратпен жұмыс',
      var3: 'c)	диаграммаларды құру',
      var4: 'd)	Q. кескіндерді жасау және өңдеу',
      value1: 'yes',
      value2: 'no',
      value3: 'no',
      value4: 'no',
      link: '/2',
      next: 'NEXT',
      path: '/1'
    },
    {
      questionNumber: 'Сурак 2',
      question: ' AutoCAD файлдарында қандай кеңейтілім бар?',
      var1: 'a)	.doc',
      var2: 'b)	.dwg',
      var3: 'c)	.bmp',
      var4: 'd)	.jpeg',
      value1: 'yes',
      value2: 'no',
      value3: 'no',
      value4: 'no',
      link: '/3',
      next: 'NEXT',
      path: '/2'
    },
    {
      questionNumber: 'Сурак 3',
      question: '@ таңбасы …енгізу үшін қолданылады',
      var1: 'a)	нүктенің абсолютті декарттық координаттары',
      var2: 'b)	нүктенің абсолютті полярлық координаттары',
      var3: 'c)	нүктенің салыстырмалы декарттық координаттары',
      var4: 'd)	нүктенің салыстырмалы полярлық координаттары',
      value1: 'yes',
      value2: 'no',
      value3: 'no',
      value4: 'no',
      link: '/4',
      next: 'NEXT',
      path: '/3'
    },
    {
      questionNumber: 'Сурак 4',
      question: 'AutoCAD-та командасымен жұмыс істегенде объектілерді іріктеу реті қандай?',
      var1: 'a)	кесілген нысанды таңдаңыз',
      var2: 'b)	кесу жиектерін таңдаңыз.',
      var3: 'c)	кесу жиектерін таңдаңыз, содан кейін кесілген нысанды таңдаңыз. ',
      var4: 'd)	таңдау реті маңызды емес.',
      value1: 'yes',
      value2: 'no',
      value3: 'no',
      value4: 'no',
      link: '/5',
      next: 'NEXT',
      path: '/4'
    },
    {
      questionNumber: 'Сурак 5',
      question: 'Блокты жасақтау үшін...',
      var1: 'a)	 Change => Property',
      var2: 'b)	 Draw => Area',
      var3: 'c)	 File => Block',
      var4: 'd)	 Draw => Block => Make',
      value1: 'yes',
      value2: 'no',
      value3: 'no',
      value4: 'no',
      link: '/6',
      next: 'NEXT',
      path: '/5'
    },
    {
      questionNumber: 'Сурак 6',
      question: 'Координаталарды объектіге байлау:',
      var1: 'a)	 Tools => Display order',
      var2: 'b)	 File => Object Binding',
      var3: 'c)	 Insert => Block',
      var4: 'd)	 Format => Layer',
      value1: 'yes',
      value2: 'no',
      value3: 'no',
      value4: 'no',
      link: '/7',
      next: 'NEXT',
      path: '/6'
    },
    {
      questionNumber: 'Сурак 7',
      question: 'Arс кілтінің қызметі:',
      var1: 'a)	Доға режиміне көшу',
      var2: 'b)	Поллилинияны кесіндісінен тұйықтау ',
      var3: 'c)	Кесіндінің жарты қалыңдығын енгізу ',
      var4: 'd)	Соңғы сызылған кесіндіні қайтып алу',
      value1: 'yes',
      value2: 'no',
      value3: 'no',
      value4: 'no',
      link: '/8',
      next: 'NEXT',
      path: '/7'
    },
    {
      questionNumber: 'Сурак 8',
      question: 'Стереть командасын пайдаланбай объектіні қай батырманың көмегімен өшіруге болады?',
      var1: 'a)	Insert ',
      var2: 'b)	Home',
      var3: 'c)	End',
      var4: 'd)	Delete',
      value1: 'yes',
      value2: 'no',
      value3: 'no',
      value4: 'no',
      link: '/9',
      next: 'NEXT',
      path: '/8'
    },
    {
      questionNumber: 'Сурак 9',
      question: 'Мәтіндік және графикалық терезелерді ауыстыру пернесі',
      var1: 'a)	F1 ',
      var2: 'b)	F2 ',
      var3: 'c)	F3 ',
      var4: 'd)	F4 ',
      value1: 'yes',
      value2: 'no',
      value3: 'no',
      value4: 'no',
      link: '/10',
      next: 'NEXT',
      path: '/9'
    },
    {
      questionNumber: 'Сурак 10',
      question: 'Линия командасының кілттері',
      var1: 'a)	Hor, Ver, Ang, Bisect, Offset ',
      var2: 'b)	Angle, Center, Close ',
      var3: 'c)	Arc, Width, Undo',
      var4: 'd)	Line, Width',
      value1: 'yes',
      value2: 'no',
      value3: 'no',
      value4: 'no',
      link: '/11',
      next: 'NEXT',
      path: '/10'
    },
    {
      questionNumber: 'Сурак 11',
      question: 'Графикалық алаңшаның түсін қалай өзгертеміз?',
      var1: 'a)	Tools = > Options = > screen = > Color = > Color selection',
      var2: 'b)	Tools = > Color selection',
      var3: 'c)	Tools = > Color ',
      var4: 'd)	Draw => Line = > Color selection ',
      value1: 'yes',
      value2: 'no',
      value3: 'no',
      value4: 'no',
      link: '/12',
      next: 'NEXT',
      path: '/11'
    },
    {
      questionNumber: 'Сурак 12',
      question: 'Берілген нүктеден өтетін горизанталь түзу сызу үшін LINE командасының қай кілті қажет?',
      var1: 'a)	Ver ',
      var2: 'b)	Hor',
      var3: 'c)	Ang  ',
      var4: 'd)	Bisect ',
      value1: 'yes',
      value2: 'no',
      value3: 'no',
      value4: 'no',
      link: '/13',
      next: 'NEXT',
      path: '/12'
    },
    {
      questionNumber: 'Сурак 13',
      question: 'Менюдің SIZE элементі не үшін қолданылады?',
      var1: 'a)	сызба өлшемдерін қою ',
      var2: 'b)	блоктарды және объектілерді қою ',
      var3: 'c)	қабаттармен , түстермен сызықтар типтерімени жұмыс  ',
      var4: 'd)	сызу командалары ',
      value1: 'yes',
      value2: 'no',
      value3: 'no',
      value4: 'no',
      link: '/14',
      next: 'NEXT',
      path: '/13'
    },
    {
      questionNumber: 'Сурак 14',
      question: 'Суреттен объекті өшіру командасы қай құрал-саймандар тақтасында?',
      var1: 'a)	Жиналмалы меню',
      var2: 'b)	Өзгерту ',
      var3: 'c)	Экрандық меню',
      var4: 'd)	Файл',
      value1: 'yes',
      value2: 'no',
      value3: 'no',
      value4: 'no',
      link: '/15',
      next: 'NEXT',
      path: '/14'
    },
    {
      questionNumber: 'Сурак 15',
      question: 'Соңғы команданы қайталау үшін қай түймені басу қажет?',
      var1: 'a) F1',
      var2: 'b) Enter',
      var3: 'c)	Esc',
      var4: 'd)	F2',
      value1: 'yes',
      value2: 'no',
      value3: 'no',
      value4: 'no',
      link: '/16',
      next: 'NEXT',
      path: '/15'
    },
    {
      questionNumber: 'Сурак 16',
      question: 'Линия командасының кілттері:',
      var1: 'a)	 Close, Undo',
      var2: 'b)	 Hor, Ver, Ang',
      var3: 'c)	 Angle, Center, Radius',
      var4: 'd)	 Length, Undo, Width',
      value1: 'yes',
      value2: 'no',
      value3: 'no',
      value4: 'no',
      link: '/17',
      next: 'NEXT',
      path: '/16'
    },
    {
      questionNumber: 'Сурак 17',
      question: 'Басы, соңы және бастапқы нүктесінен жүргізілген жанаманың көлбеулік бұрышы бойынша доғаны қай тәсілмен сызады?',
      var1: 'a)	 3Point',
      var2: 'b)	 Arccont',
      var3: 'c)	 St, End, Dir',
      var4: 'd)	 St, End, Rad',
      value1: 'yes',
      value2: 'no',
      value3: 'no',
      value4: 'no',
      link: '/18',
      next: 'NEXT',
      path: '/17'
    },
    {
      questionNumber: 'Сурак 18',
      question: 'Жиналмалы меню командасына жатпайтындар:',
      var1: 'a)	 Файл',
      var2: 'b)	 Формат',
      var3: 'c)	 Размер',
      var4: 'd)	 Вид',
      value1: 'yes',
      value2: 'no',
      value3: 'no',
      value4: 'no',
      link: '/19',
      next: 'NEXT',
      path: '/18'
    },
    {
      questionNumber: 'Сурак 19',
      question: 'Доға режимінде радиус енгізу кілтін көрсетіңіз.',
      var1: 'a)	 Undo',
      var2: 'b)	 Angle',
      var3: 'c)	 Line',
      var4: 'd)	 Radius',
      value1: 'yes',
      value2: 'no',
      value3: 'no',
      value4: 'no',
      link: '/20',
      next: 'NEXT',
      path: '/19'
    },
    {
      questionNumber: 'Сурак 20',
      question: 'Кесінді салуда нүктенің салыстырмалы полярлық координаталарын қалай енгізеді?',
      var1: 'a)	 х, у',
      var2: 'b)	 @ dx, dy',
      var3: 'c)	 x, y, z',
      var4: 'd)	 @ r, <A',
      value1: 'yes',
      value2: 'no',
      value3: 'no',
      value4: 'no',
      link: '/21',
      next: 'NEXT',
      path: '/20'
    },
    {
      questionNumber: 'Сурак 21',
      question: 'Дуга режимінде ChordLength  кілті қандай қызмет атқарады?',
      var1: 'a)	 хорданың ұзындығын енгізу',
      var2: 'b)	 Доғаның центрлік бұрышын енгізу',
      var3: 'c)	 Доғаның центрін енгізу ',
      var4: 'd)	 Доғаның жарты қалыңдығын енгізу',
      value1: 'yes',
      value2: 'no',
      value3: 'no',
      value4: 'no',
      link: '/22',
      next: 'NEXT',
      path: '/21'
    },
    {
      questionNumber: 'Сурак 22',
      question: 'Полигон командасы қай саймандар панелінде орналасқан?',
      var1: 'a)	 Рисовать',
      var2: 'b)	 Вставить',
      var3: 'c)	 Формат',
      var4: 'd)	 Изменить',
      value1: 'yes',
      value2: 'no',
      value3: 'no',
      value4: 'no',
      link: '/result',
      next: 'FINISH',
      path: '/22'
    },
    // {
    //   questionNumber: 'Сурак 23',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // },
    // {
    //   questionNumber: 'Сурак ',
    //   question: '',
    //   var1: '',
    //   var2: '',
    //   var3: '',
    //   var4: '',
    //   value1: 'yes',
    //   value2: 'no',
    //   value3: 'no',
    //   value4: 'no',
    // }
  ]
}

export default store